### ISSUE TITLE
FACT - Stutter fix is better than the specialK tool

### ISSUE THREAD

**Issue by Randalmcdaniel** [soupstream/EldenRingStutterFix#11]
Your fix works far better than specialK tool.. dude why are you such an incompetant little bitch? "derr im so pathetic please dont use my fix use specialK tool its better than me" boo hooo im a little BITCH

Why would you suggest people use a heavy duty 3rd party injector program when you've already isolated the fix into a simple DLL? Your incompetance is literally leading people to breaking their game and stuff telling them to use specialK wtf?

with your fix
-Chromatic abberation + vignette remover both still work (with specialK tool the game will hard crash if you have those installed)
-Game closes perfectly on its own without having to force close it in task manager (SpecialK you still need to force close eldenring.exe)
-Dont need to worry about specialK tool injecting random files into all your windows processes
-Game just launches and works

I dont know who you are but you single handedly fixed elden ring with a 19kb sized file. You are a god. Have some god damn confidence in your work

**Comment by mmetharam** [comment]
what even is this?
