### ISSUE TITLE
getting an error of "Proc not found: D3D12GetInterface"

### ISSUE THREAD

**Issue by nommi** [soupstream/EldenRingStutterFix#2]
Getting this error from lauching the game exe directly with EAC disabled, wasn't able to launch the game with this installed unfortunately.

**Comment by soupstream** [comment]
I've published a new version that should fix this: https://github.com/soupstream/EldenRingStutterFix/releases/tag/v1.0.2

**Comment by soupstream** [comment]
Which Windows 10 version are you on? (the number in Settings > System > About > Version)

**Comment by soupstream** [comment]
Seems like this is a duplicate of https://github.com/soupstream/EldenRingStutterFix/issues/3, closing
