### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Spartan5345jhj** [soupstream/EldenRingStutterFix#6]
Game don't start EAC disabled my video card is mx 150

**Comment by soupstream** [comment]
Looking into this, see https://github.com/soupstream/EldenRingStutterFix/issues/3

**Comment by Spartan5345jhj** [comment]
GPU: MX 150 4 gig
CPU: Intel core i 3 7100
Win 10 1809 pro
potato but at 720p medium lowe 30-40 fps

чт, 17 мар. 2022 г. в 05:55, soupstream ***@***.***>:
