### ISSUE TITLE
Realy Nice Job! 

### ISSUE THREAD

**Issue by RealSankiri** [soupstream/EldenRingStutterFix#7]
I could test your awesome patch on my workstation for 2 hours until Patch 1.0.3 came out; on my laptop and it was almost perfect or it is perfect. 

Normaly on my Laptop I reach 3.4 ghz and the game was 80% smooth.
Now I play on 2.7 ghz with significant better perfomance and a little less  of temperture. It is like 95 % smooth and only 1% stutter almost rare. 

Great work!

I wish u nice day! (dos it work with 1.03?)

**Comment by soupstream** [comment]
Glad it helped! It should still work with 1.03 (not sure if FromSoft has made these fixes on their end yet).
