### ISSUE TITLE
Doesn't work anymore for patch 1.03?

### ISSUE THREAD

**Issue by steffen-dc** [soupstream/EldenRingStutterFix#8]

**Comment by Spark9999** [comment]
Yeah, same for me

**Comment by RaxleAlucard** [comment]
Same here doesn't work anymore

**Comment by soupstream** [comment]
Meaning the game is stuttering again? Or is it crashing?

**Comment by random29** [comment]
Yea, totally useless on 1.03.1
Crashes the game completely, I even reinstalled it from scratch
Just crash

**Comment by Spark9999** [comment]
It's not crashing for me, just that stuttering exists
Like some specific scenarios would include, when u get on ur horse from the stormville shack grace point and ride towards the big giant on the right side, it slightly stutters
Another scenario is, when those big giant flowers shoot those glintstone magic pebbles at you, like multiple flowers and if you turn back while running or even escaping those shots then the game is gonna stutter, all my gpu bound settings have been lowered (gtx 1650, should be more than capable) and my cpu bound settings, high or low does not matter(i5-10400, 16gb ram)

**Comment by Jivko1212** [comment]
I found a way to stop the stuttering on my system. If I play with keyboard and mouse I get no stuttering (I was using this fix along with the Elden Ring Frame Rate Unlocker). As soon as I turn on my controller, the game starts to stutter (it pauses two times next to each other for about half a second). I had a similar issue with Sekiro, which was rectified by Special K.

**Comment by Spark9999** [comment]
> I found a way to stop the stuttering on my system. If I play with keyboard and mouse I get no stuttering (I was using this fix along with the Elden Ring Frame Rate Unlocker). As soon as I turn on my controller, the game starts to stutter (it pauses two times next to each other for about half a second). I had a similar issue with Sekiro, which was rectified by Special K.

I'll try this... I don't use my controller, but I have its Bluetooth dongle connected to my pc always, so any game would detect a controller. I'll unplug the dongle and check if the stuttering gets resolved.

**Comment by GoldenLumia** [comment]
Gonna offer a bit of dissent and say it does not crash my game and does seem to be running my game better.

**Comment by Dellhex** [comment]
please update it! (x2)

**Comment by soupstream** [comment]
I've updated it to fix a crash (which isn't related to 1.03 but might be what was reported here). If it still isn't improving performance for you I recommend trying [Special K](https://discourse.differentk.fyi/t/download-special-k/1461) which implements the same fixes and more.
